### PR TITLE
add province and cma

### PR DESCRIPTION
**Pull request by dshkol**
file706925372908

Adds CMA and Province below the CSD name. Have to be a bit flexible with the space in the middle because of those towns with long French names that can mess things up. There's also room for an additional data point under population now, perhaps a 10-yr population change figure? 

Still to do:
* Add CMA and Province to the barbell plots and a legend

### CODE REVIEW

**Comment by mountainMath** [comment]
I like it, the second row is a good option. On the right we could do CMA population next to 10 year population change to keep in style with the two barbell graphs below?

**Comment by dshkol** [comment]
Can you clarify what you want to see exactly? Under the pop figure, do you want a numerical or graphical representation of that change, like the barbell below, or using text? (+10% /+15% CMA) I think text would be cleaner.

**Comment by mountainMath** [comment]
I was thinking text, agree that that's cleaner. But for the population change the barbell might work well. So we would only have it in the bottom one?

**Comment by dshkol** [comment]
Can you mock it up for me?

**Comment by mountainMath** [comment]
7f73c362-6801-4845-8ee9-c60052aa69c3

Thinking we just add something like “(12% of CMA)” or (12% of Toronto CMA) underneath the Population text. And another line (maybe first) to the second barbell plot for population change.

Also, we still need the municipal type in the city name, at least for the non-unique city names like Langley or North Vancouver, but also for cases where city and CMA share same name like Vancouver or Toronto. We could just test for that and only add when needed. I would also add “(CMA)” behind the CMA name, or maybe write “Metro” in front. Just for clarity.

**Comment by dshkol** [comment]
file706932246f7a

**Pull request merged**
